### ISSUE TITLE
Combine several requests

### ISSUE THREAD

**Issue by Gomez** [collective/collective.webhook#3]
Its working great to get a gatsby site updated. Unfortunately the build pipeline of our CI server gets flooded,  is there a way to send only one request every 15 min for example?

**Comment by datakurre** [comment]
CI does not support throttling builds?  (Or cancel queued builds?) Maybe TAL content rule condition? 🤔 (Eg. only allow if less that X objects have been updated in some timeframe.)

**Comment by Gomez** [comment]
Thanks datakurre. I added a helperview and call it as TALES condition.
Unfortunately Gitlab CI does not have throttling builds.

**Comment by datakurre** [comment]
This still didn't work for triggered builds? https://docs.gitlab.com/ce/user/project/pipelines/settings.html#auto-cancel-pending-pipelines

What kind of heuristics you end up using for throttling?

**Comment by Gomez** [comment]
Looks like "Auto-cancel pending pipelines" does not work on API triggered runs. 

I added a 15min timer, will post after i setup the cron part.

**Comment by datakurre** [comment]
Next idea: Is there an API to cancel pipelines? So that content rule could first cancel and then trigger a new 🤔 (And in the worst case never complete 🙈)

**Comment by Gomez** [comment]
Newer gitlab versions now cancel queued builds (on API calls). 

Here is my code to combine requests i used before:

```
class HelperView(BrowserView):
    """ Exposes methods for expression conditions """

    def webhook_send_allowed(self):
        """ Checks if webhook call is needed
        """

        portal = api.portal.get()
        annotations = IAnnotations(portal)
        value = annotations.get(WEBHOOK_LAST_SEND_KEY, None)
        if value is None:
            value = annotations[WEBHOOK_LAST_SEND_KEY] = datetime.utcnow()
            return True
        time_diff = timedelta(minutes=15)
        if value + time_diff < datetime.utcnow():
            annotations[WEBHOOK_LAST_SEND_KEY] = None
            return False
```

Plus a TALES expression on the content rule: `portal/helper_view/webhook_send_allowed`

(Still a cron is needed to cleanup the webhook cache)
